[package]
name = "shakmaty"
version = "0.0.4"
description = "A library for chess move generation"
repository = "https://github.com/niklasf/shakmaty"
readme = "README.md"
license = "GPL-3.0+"
authors = ["Niklas Fiekas <niklas.fiekas@backscattering.de>"]
categories = ["games", "parsing"]
keywords = ["chess"]
build = "src/build.rs"

[dependencies]
option-filter = "1.0"

[dependencies.arrayvec]
git = "https://github.com/bluss/arrayvec.git"
rev = "7deb5c5db4c631baa6662049b633aac83819b0a4"
features = ["use_union"]

[badges]
travis-ci = { repository = "shakmaty", branch = "master" }
