[package]
name = "shakmaty"
version = "0.0.1"
description = "A library for chess move generation"
homepage = "https://github.com/niklasf/shakmaty"
repository = "https://github.com/niklasf/shakmaty"
readme = "README.md"
license = "GPL3"
authors = [ "Niklas Fiekas <niklas.fiekas@backscattering.de>" ]

[dependencies]
lazy_static = "0.2"

[badges]
travis-ci = { repository = "shakmaty", branch = "master" }
