[package]
name = "shakmaty"
version = "0.0.10" # remember to update html_root_url
description = "A library for chess move generation"
documentation = "https://docs.rs/shakmaty"
homepage = "https://github.com/niklasf/shakmaty"
repository = "https://github.com/niklasf/shakmaty"
readme = "README.md"
license = "GPL-3.0+"
authors = ["Niklas Fiekas <niklas.fiekas@backscattering.de>"]
categories = ["games", "parsing"]
keywords = ["chess"]
build = "src/build.rs"

[dependencies]
option-filter = "1.0"
btoi = "0.1"

[dependencies.arrayvec]
version = "0.4"
features = ["use_union"]

[badges]
travis-ci = { repository = "niklasf/shakmaty", branch = "master" }
