[package]
name = "shakmaty"
version = "0.20.1" # remember to update changelog and html_root_url
description = "Chess and chess variant rules and operations"
repository = "https://github.com/niklasf/shakmaty"
readme = "README.md"
license = "GPL-3.0+"
authors = ["Niklas Fiekas <niklas.fiekas@backscattering.de>"]
categories = ["games", "parser-implementations"]
keywords = ["chess", "lichess"]
build = "src/build.rs"
edition = "2021"
rust-version = "1.56"

[features]
default = []
step = []
variant = []

[[bench]]
name = "benches"
harness = false

[lib]
bench = false

[dependencies]
bitflags = "1"
btoi = "0.4"
arrayvec = "0.7"

[dev-dependencies]
iai = "0.1"

[package.metadata.docs.rs]
all-features = true
rustdoc-args = ["--cfg", "docs_rs"]
