name: Test

on:
  - push
  - pull_request

jobs:
  test:
    strategy:
      matrix:
        toolchain:
          - "1.60.0"
          - "stable"
          - "beta"
          - "nightly"
        features:
          - ""
          - "--features variant"
          - "--features alloc"
          - "--features std"
          - "--features alloc,variant"
          - "--features std,variant"
        include:
          - toolchain: "nightly"
            features: "--features step"
          - toolchain: "nightly"
            features: "--features alloc,step"
          - toolchain: "nightly"
            features: "--features std,step"
          - toolchain: "nightly"
            features: "--features step,variant"
          - toolchain: "nightly"
            features: "--features alloc,step,variant"
          - toolchain: "nightly"
            features: "--features std,step,variant"
          - toolchain: "nightly"
    runs-on: ubuntu-latest
    steps:
      - run: sudo apt-get update && sudo apt-get install -y valgrind
      - uses: actions/checkout@v2
      - uses: actions-rs/toolchain@v1
        with:
          profile: minimal
          toolchain: ${{ matrix.toolchain }}
          override: true
      - uses: actions-rs/cargo@v1
        with:
          command: test
          args: --no-default-features ${{ matrix.features }}
      - uses: actions-rs/cargo@v1
        with:
          command: bench
  docs:
    strategy:
      matrix:
        docs:
          - ""
          - "--features step"
          - "--features variant"
          - "--features step,variant"
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions-rs/toolchain@v1
        with:
          profile: minimal
          toolchain: nightly
          override: true
      - uses: actions-rs/cargo@v1
        with:
          command: doc
          args: ${{ matrix.docs }}
